apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-contour-cluster-issuer
  namespace: tanzu-system-ingress
spec:
  acme:
    email: kwan@vmware.com
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        clouddns:
          # The ID of the GCP project
          project: pa-qwan
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: certbot-gcp-service-account
            key: certbot-gcp-service-account.json

